return {
    Weapons = {
        Bow = {'Compound Bow','Raven Bow','Dream Bow','Bat Bow','Frostbite Bow','Key Bow'},
        ['Assault Rifle'] = {'AKEY-47','AUG','Ginerbread AUG','Tommy Gun','AK-47','Boneclaw Rifle','Phoenix Rifle','10B Visits'},
        Chainsaw = {'Blobsaw','Handsaws','Mega Drill','Buzzsaw','Festive Buzzsaw'},
        RPG = {'Nuke Launcher','RPKEY','Spaceship Launcher','Squid Launcher','Pumpkin Launcher','Firework Launcher','Pencil Launcher'},
        ['Burst Rifle'] = {'Aqua Burst','Electro Rifle','FAMAS','Spectral Burst','Pine Burst','Pixel Burst'},
        Exogun = {'Singularity','Wondergun','Ray Gun','Repulsor','Exogourd','Midnight Festive Exogun'},
        Fists = {'Boxing Gloves','Brass Knuckles','Fists Of Hurt','Pumpkin Claws','Festive Fists'},
        Flamethrower = {'Lamethrower','Pixel Flamethrower','Glitterthrower',"Jack O'Trower",'Snowblower'},
        ['Flare Gun'] = {'Dynamite Gun','Firework Gun','Banana Flare','Vexed Flare Gun','Wrapped Flare Gun'},
        ['Freeze Ray'] = {'Bubble Ray','Temporal Ray','Gum Ray','Spider Ray','Wrapped Freeze Ray'},
        Grenade = {'Water Balloon','Whoopee Cushion','Dynamite','Soul Grenade','Jingle Grenade','Keynade'},
        ['Grenade Launcher'] = {'Swashbuckler','Uranium Launcher','Gearnade Launcher','Skull Launcher','Snowball Launcher'},
        Handgun = {'Hand Gun','Pixel Handgun','Blaster','Gingerbread Handgun','Gumball Handgun','Pumpkin Handgun','Stealth Handgun'},
        Katana = {'Lightning Bolt','Saber','Stellar Katana',"Devil's Trident",'2025 Katana','Pixel Katana','Keytana'},
        Minigun = {'Lasergun 3000','Pixel Minigun','Fighter Jet','Pumpkin Minigun','Wrapped Minigun'},
        ['Paintball Gun'] = {'Boba Gun','Slime Gun','Ketchup Gun','Brain Gun','Snowball Gun'},
        Revolver = {'Sheriff','Desert Eagle','Peppergun','Boneclaw Revolver','Peppermint Sheriff','Keyvolver'},
        Slingshot = {'Goalpost','Stick','Harp','Boneshot','Reindeer Slingshot'},
        ['Subspace Tripmine'] = {"Don't Press",'Spring','DIY Tripmine','Trick or Treat','Dev-in-the-Box'},
        Uzi = {'Electro Uzi','Water Uzi','Money Gun','Demon Uzi','Pine Uzi','Keyzi'},
        Sniper = {'Pixel Sniper','Hyper Sniper','Event Horizon','Eyething Sniper','Gingerbread Sniper','Keyper'},
        Knife = {'Karambit','Chancla','Balisong','Machete','Candy Cane'},
        Crossbow = {'Pixel Crossbow','Harpoon Crossbow','Violin Crossbow','Frostbite Crossbow'},
        ['Energy Rifle'] = {'Hacker Rifle','Hydro Rifle','Void Rifle','2025 Energy Rifle','Apex Rifle'},
        Gunblade = {'Hyper Gunblade','Crude Gunblade','Gunsaw',"Elf's Gunblade"},
        Shotgun = {'Balloon Shotgun','Hyper Shotgun','Cactus Shotgun','Broomstick','Wrapped Shotgun','Shotkey'},
        Daggers = {'Aces','Paper Planes','Shurikens','Cookies','Crystal Daggers'},
        ['Energy Pistols'] = {'Hacker Pistols','Void Pistols','Hydro Pistols','2025 Energy Pistols','Apex Pistols'},
        Shorty = {'Not So Shorty','Lovely Shorty','Balloon Shorty','Demon Shorty','Wrapped Shorty','Too Shorty'},
        Spray = {'Lovely Spray','Nailgun','Spray Bottle','Pine Spray'},
        ['Battle Axe'] = {'The Shred','Ban Axe','Cerulean Axe','Nordic Axe'},
        ['Riot Shield'] = {'Door','Energy Shield','Masterpiece','Sled'},
        Scythe = {'Scythe of Death','Anchor','Sakura Scythe','Bat Scythe','Cryo Scythe','Keythe','Bug Net'},
        Trower = {'Plastic Shovel','Garden Shovel','Paintbrush','Pumpkin Carver','Snow Shovel'},
        Flashbang = {'Disco ball','Camera','Lightbulb','Skullbang','Shining Star','Pixel Flashbang'},
        ['Jump Pad'] = {'Trampoline','Bounce House','Shady Chicken Sandwich'},
        Medkit = {'Sandwich','Laptop','Medkitty','Bucket of Candy','Milk & Cookies','Briefcase'},
        Molotov = {'Coffee','Torch','Lava Lamp','Vexed Candle','Hot Coals'},
        Satchel = {'Advanced Satchel','Notebook Satchel',"Bag O' Money",'Suspicious Gift'},
        ['Smoke Grenade'] = {'Emoji Cloud','Balance','Hourglass','Eyeball','Snowglobe'},
        ['War Horn'] = {'Trumpet','Megaphone','Air Horn','Mammoth Horn'},
    },
    DefaultHitParts = {
        'Head','LeftFoot','LeftHand','LeftLowerArm','LeftLowerLeg','LeftUpperArm','LowerTorso','RightFoot','RightHand','RightLowerArm','RightLowerLeg','RightUpperArm','RightUpperLeg','UpperTorso','HitboxBody','FakeMass','HitboxBodySmall','HumanoidRootPart',
    },
    Colors = {
        MainFrame = Color3.fromRGB(20,20,25),
        TopBar = Color3.fromRGB(25,25,30),
        Sidebar = Color3.fromRGB(30,30,35),
        ContentFrame = Color3.fromRGB(40,40,45),
        Button = Color3.fromRGB(50,50,55),
        ButtonHover = Color3.fromRGB(70,70,75),
        ButtonText = Color3.fromRGB(220,220,220),
        TitleText = Color3.fromRGB(255,255,255),
        CloseButton = Color3.fromRGB(180,40,40),
        ToggleOn = Color3.fromRGB(100,180,100),
        ToggleOff = Color3.fromRGB(220,100,100),
        ToggleCircle = Color3.fromRGB(255,255,255),
        Selected = Color3.fromRGB(0,170,255),
    },
    ESPColors = {
        Box = Color3.new(0, 1, 0),
        BoxOutline = Color3.new(0, 0, 0),
        Cham = Color3.new(0, 1, 0),
        ChamOutline = Color3.new(0, 0.5, 0),
        Name = Color3.new(1, 1, 1),
        Distance = Color3.new(1, 1, 1),
        HealthBar = Color3.new(0, 1, 0),
        HealthBarBackground = Color3.new(0, 0, 0),
        Tracer = Color3.new(0, 1, 0),
        Skull = Color3.new(1, 1, 1),
        TeamCheck = true,
    },
    ESPConfig = {
        EnableBox = true,
        EnableCham = true,
        EnableName = true,
        EnableDistance = true,
        EnableHealthBar = true,
        EnableTracer = false,
        EnableSkull = false,
        EnableHeadOffset = false,
        HealthBarPosition = "left",
        HealthBarStyle = "classic",
        BoxStyle = "box",
        BoxThickness = 2,
        DistanceType = "studs",
    },
    AimBotConfig = {
        EnableAimbot = false,
        EnableTrigger = false,
        EnableSilentAim = false,
        EnableSpinBot = false,
        EnableWallCheck = true,
        EnablePrediction = false,
        FOVSize = 100,
        SmoothAmount = 0,
        PredictionAmount = 0,
        HitPart = "HitboxHead",
        TriggerKey = "P",
        SpinSpeed = 25,
    },
    PlayerConfig = {
        EnableSpeedHack = false,
        SpeedValue = 60,
        EnableInfiniteJump = false,
        EnableNoClip = false,
        EnableThirdPerson = false,
        ThirdPersonDistance = 10,
        EnableFly = false,
        FlySpeed = 50,
        FlyNoClip = false,
    },
    TeleportConfig = {
        EnableTeleportToEnemy = false,
        EnableTeleportBehind = false,
        BehindOffset = -5,
    },
    RageConfig = {
        EnableNoCooldown = false,
        EnableNoSpread = false,
        EnableNoRecoil = false,
        EnableInstantHit = false,
        EnableBulletTracers = false,
    },
    EffectsConfig = {
        EnableDisableFlashbang = false,
        EnableDisableSmoke = false,
        EnableDisablePaintball = false,
        EnableAntiAFK = false,
        EnableRemoveRecoil = false,
    },
    HitNotifyConfig = {
        EnableHitNotify = true,
        ShowDamage = true,
        ShowKill = true,
        ShowHeadshot = true,
        EnableSound = true,
        NotifyPosition = "right",
        MaxNotifications = 5,
        DamageColor = Color3.new(1, 0.3, 0.3),
        KillColor = Color3.new(1, 0, 0),
        HeadshotColor = Color3.new(1, 0.8, 0),
    },
    CameraConfig = {
        EnableFOV = false,
        FOVValue = 70,
        MinFOV = 10,
        MaxFOV = 120,
    },
    DefaultSettings = {
        WeaponSkinSettings = {},
        CustomSkinSettings = {},
        katanaCounter = true,
        AimbotEnabled = false,
        ESPEnabled = false,
        FOVSize = 100,
        FlySpeed = 50,
        FlyNoClip = false,
        TriggerEnabled = false,
        DisableShootCooldown = false,
        DisableGunSpread = false,
        DisableGunRecoil = false,
    },
    MenuTabs = {'Aimbot','Visuals','Player','Teleport','Useful Features','Skin Changer','Rage Mode','Hit Notify','Extras','Settings'},
}